export const CREATE_TUTORIAL = "CREATE_TASK";
export const RETRIEVE_TUTORIALS = "RETRIEVE_TASKS";
export const UPDATE_TUTORIAL = "UPDATE_TASK";
export const DELETE_TUTORIAL = "DELETE_TASK";
export const DELETE_ALL_TUTORIALS = "DELETE_ALL_TASKS";